### ISSUE TITLE
Validación al agregar objeto a la tabla de símbolos

### ISSUE THREAD

**Issue by vkslax** [ericknavarro/InterpreteSencillo#5]
Hay un pequeño error al declarar una variable, ya que no se valida que esta no este ya declarada. Se propone la implementación del método que haga dicha validación.

**Comment by rjanixz** [comment]
Muy buena observación @vkslax. no olides hacer tu propuesta de código con su respectivo pull request

**Comment by rjanixz** [comment]
PR https://github.com/ericknavarro/InterpreteSencillo/pull/13

**Comment by rjanixz** [comment]
Muchas gracias por tu aporte @vkslax, por favor envíarme un correo con la siguiente información:

carnet, nombre, usuario de github, sección, repositorio, número de issue y número de pull request.
