### ISSUE TITLE
Mejora en operadores relacionales 

### ISSUE THREAD

**Issue by vkslax** [ericknavarro/InterpreteSencillo#6]
Se propone agregar el manejo de los operadores == y !=, ya que el proyecto podría seguir manteniendo su sencillez y al contar únicamente con < y >, estos podrían no ser suficientes para todo tipo de operación que se quiera probar.

**Comment by vkslax** [comment]
También podría ser posible agregar los operadores <= y >=, aunque esto ya iría aumentando un poco más la gramática y la sencillez del proyecto, que considero que es también parte del objetivo de compartirlo, se va perdiendo un poco.

**Comment by rjanixz** [comment]
Muy buenas tus observaciones @vkslax recorda hacer la propuesta de códido correspondiente haciendo un opull request

**Comment by rjanixz** [comment]
PR https://github.com/ericknavarro/InterpreteSencillo/pull/14

**Comment by rjanixz** [comment]
Muchas gracias por tu aporte @vkslax, por favor envíarme un correo con la siguiente información:

carnet, nombre, usuario de github, sección, repositorio, número de issue y número de pull request.
