### ISSUE TITLE
Mejora en clase Simbolo

### ISSUE THREAD

**Issue by NedHerrera** [ericknavarro/InterpreteSencillo#7]
Propongo agregar un método setTipo en la clase Símbolo para hacer el cambio de tipo de una variable (para posibles usos en el casteo). Con esto se agilizaría la realización de dicha función. 

Por: 201602870
Saludos.

**Comment by rjanixz** [comment]
@NeDGUndPanzer , el tipo de las variables usualmente no cambia durante la ejecución (a menos que el lenguaje lo permita) en todo caso, para los casteos no es el tipo de la variable el que cambia, sino el valor en si. Por ejemplo:

`int numeroEntero = 1.23`

Se trata de asignar un valor decimal a una variable de tipo entero, lo cual no es posible, para esto se requiere de un casteo explícito:

`int numeroEntero = (int)1.23`

Por lo que la variable `numeroEntero` tendrá el valor de `1`, el cambio lo sufre el valor no el tipo de la variable.

Saludos.
