### ISSUE TITLE
Agregar otro tipo de dato a la clase Simbolo

### ISSUE THREAD

**Issue by 201503440** [ericknavarro/InterpreteSencillo#8]
Seria muy util manejar otro tipo de dato en la clase simbolo para poder declarar variables de tipo cadena por ejemplo:
cadena cad;
cad = "Esto es una cadena.";
imprimir(cad);
Salida: 
Esto es una cadena.

**Comment by rjanixz** [comment]
pull request para este issue: https://github.com/ericknavarro/InterpreteSencillo/pull/11

**Comment by rjanixz** [comment]
Se cierra issue por falta de respuesta en solicitud de cambios en pr
