### ISSUE TITLE
Implementacion de entornos

### ISSUE THREAD

**Issue by WillyAlberto** [ericknavarro/InterpreteSencillo#9]
cuando se ejecute un bloque de codigo a la hora de crear la tabla de simbolos local, en vez de agregar todo lo anterior hay que enlazarla a la tabla padre para el manejo de entornos y a la vez poder verificar de manera mas efectiva si una variable ya existe o no

**Comment by rjanixz** [comment]
Se cierra issue por falta de pull request.

@WillyAlberto por favor abrir de nuevo el issue si desarrolla la funcionalidad
